server:
  port: 80

spring:
  application:
    name: cloud-order-service  # 服务名
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    register-with-eureka: true  # 表示是否将自己注册到注册中心，默认true
    fetch-registry: true  # 是否从eurekaServer抓取已有的注册信息，默认为true（集群必须设置true，配合ribbon使用堵负载均衡）
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/
  instance:
    instance-id: order80
    prefer-ip-address: true