server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xiaofuverygood/springcloud-config.git #GitHub上面git仓库SSH地址
          #搜索的目录
          search-paths:
            - springcloud-config
      #读取的分支
      label: dev

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/  # 集群版
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'