#consul服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-provider-payment

  #concul注册中心地址
  cloud:
    consul:
      host: 192.168.10.66
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        ip-address: ${spring.cloud.client.ip-address}
        heartbeat:
          enabled: true
