server:
  port: 8002  # 服务端口

spring:
  application:
    name: cloud-payment-service  # 服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver  # mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?usrUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true  # useSSL(安全协议) mysql5.7以前默认false(通过账号密码连接),true(通过证书或令牌连接)
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  type-aliases-package: org.example.springcloud.pojo  # 搜索指定包别名
  global-config:
    db-config:
      table-prefix: tb_  #全局的表名前缀。要求 表名前缀 + 实体类名 应该等于 表名称
      id-type: auto # 全局的主键生成策略。auto表示数据库主键自增

eureka:
  client:
    register-with-eureka: true  # 表示是否将自己注册到注册中心，默认true
    fetch-registry: true  # 是否从eurekaServer抓取已有的注册信息，默认为true（集群必须设置true，配合ribbon使用堵负载均衡）
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/  # 集群版
  instance:
    instance-id: payment8002  # 服务名称
    prefer-ip-address: true # 访问路径可以显示ip地址
    lease-renewal-interval-in-seconds: 1  # 客户端向服务端发送心跳的间隔时间
    lease-expiration-duration-in-seconds: 2 # 服务端最后一次收到心跳后等待时间上限,超时剔除服务
