#8004表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 8004

#服务别名——注册到zookeeper注册中心的名称
spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver  # mysql驱动包
    # url: jdbc:mysql://localhost:3306/db2019?usrUnicode=true&characterEncoding=utf-8&useSSL=false  # useSSL(安全协议) mysql5.7以前默认false(通过账号密码连接),true(通过证书或令牌连接)
    url: jdbc:mysql://localhost:3306/db2019?usrUnicode=true&characterEncoding=utf-8&useSSL=false  # useSSL(安全协议) mysql5.7以前默认false(通过账号密码连接),true(通过证书或令牌连接)
    username: root
    password: 123456
  cloud:
    zookeeper:
      connect-string: 192.168.10.66:2181
      discovery:
        instance-host: ${spring.cloud.client.ip-address} # 动态获取实例的IP地址
        instance-port: ${server.port} # 动态获取实例的端口

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  type-aliases-package: org.example.springcloud.pojo  # 搜索指定包别名
  global-config:
    db-config:
      table-prefix: tb_  #全局的表名前缀。要求 表名前缀 + 实体类名 应该等于 表名称
      id-type: auto # 全局的主键生成策略。auto表示数据库主键自增
